name: explore_places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_staggered_animations: ^1.1.1
  otp_text_field: ^1.1.1
  qr_flutter: ^4.0.0
  # CONNECTIVITY
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  cached_network_image: ^3.2.2
  html: ^0.15.1
  package_info_plus: ^1.4.2
  flutter_html: ^2.2.1
  shimmer: ^2.0.0

  # FIREBASE
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  #firebase_crashlytics:
  firebase_messaging: ^14.1.0
  google_sign_in: ^5.4.2
  the_apple_sign_in: ^1.1.1
  syncfusion_flutter_sliders: ^20.4.51


  #ICON
  flutter_vector_icons: ^2.0.0
  fl_country_code_picker: ^0.0.4

  # LAUNCH URL
  url_launcher: ^6.1.6

  #Database
  shared_preferences: ^2.0.15

  # BASE
  fluttertoast: ^8.1.1
  loading_indicator: ^3.1.0

  searchbar_animation: ^0.0.4
  #animation_search_bar: ^0.0.10

  # GOOGLE MAP
  maps_launcher: ^2.0.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  google_maps_place_picker_mb: ^2.0.0-mb.22

  # ASSETS
  image_picker: ^0.8.6
  lottie: ^2.0.0

  # ONESIGNAL NOTIFICATION
  onesignal_flutter: ^3.4.2

  # STATE MANAGEMENT
  mobx: ^2.1.2
  flutter_mobx: ^2.0.6+4

  get: ^4.6.3
  get_storage: ^2.0.3
  pretty_dio_logger: ^1.1.1
  logger: ^1.1.0
  another_flushbar: ^1.10.28
  photo_view: ^0.13.0
  dio: ^4.0.4
  encrypt: ^5.0.1
  pull_to_refresh: ^2.0.0
    # socket_io_client: ^1.0.1
  image_cropper: ^2.0.3
  intl: ^0.17.0
  fl_chart: ^0.45.0
  pin_code_fields: ^7.3.0
  qr_code_scanner:
      git:
        url: https://github.com/xeinebiu/qr_code_scanner.git
        ref: fix_break_changes_platform
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  mobx_codegen: ^2.1.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_icons:
  image_path: "assets/app_icon.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/icon/
    - assets/loader.json
